//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Ajax.Utilities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AjaxMin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AjaxMin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Ajax.Utilities.AjaxMin", typeof(AjaxMin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Anonymous].
        /// </summary>
        internal static string AnonymousName {
            get {
                return ResourceManager.GetString("AnonymousName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - starts at line {1}, col {2} {3}.
        /// </summary>
        internal static string BlockScopeHeader {
            get {
                return ResourceManager.GetString("BlockScopeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catch Scope.
        /// </summary>
        internal static string BlockTypeCatch {
            get {
                return ResourceManager.GetString("BlockTypeCatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class {0}.
        /// </summary>
        internal static string BlockTypeClass {
            get {
                return ResourceManager.GetString("BlockTypeClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lexical Scope.
        /// </summary>
        internal static string BlockTypeLexical {
            get {
                return ResourceManager.GetString("BlockTypeLexical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module {0}.
        /// </summary>
        internal static string BlockTypeModule {
            get {
                return ResourceManager.GetString("BlockTypeModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Scope.
        /// </summary>
        internal static string BlockTypeWith {
            get {
                return ResourceManager.GetString("BlockTypeWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflicting input type switches or input file extensions (JS and CSS).
        /// </summary>
        internal static string ConflictingInputType {
            get {
                return ResourceManager.GetString("ConflictingInputType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  [{1} references renamed to {0}].
        /// </summary>
        internal static string CrunchedTo {
            get {
                return ResourceManager.GetString("CrunchedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {6}{0} {1} - starts at line {2}, col {3} {4} {5}.
        /// </summary>
        internal static string FunctionHeader {
            get {
                return ResourceManager.GetString("FunctionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} references.
        /// </summary>
        internal static string FunctionInfoReferences {
            get {
                return ResourceManager.GetString("FunctionInfoReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrow Function.
        /// </summary>
        internal static string FunctionTypeArrow {
            get {
                return ResourceManager.GetString("FunctionTypeArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function Expression.
        /// </summary>
        internal static string FunctionTypeExpression {
            get {
                return ResourceManager.GetString("FunctionTypeExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function.
        /// </summary>
        internal static string FunctionTypeFunction {
            get {
                return ResourceManager.GetString("FunctionTypeFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator .
        /// </summary>
        internal static string FunctionTypeGenerator {
            get {
                return ResourceManager.GetString("FunctionTypeGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method.
        /// </summary>
        internal static string FunctionTypeMethod {
            get {
                return ResourceManager.GetString("FunctionTypeMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Get.
        /// </summary>
        internal static string FunctionTypePropGet {
            get {
                return ResourceManager.GetString("FunctionTypePropGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Set.
        /// </summary>
        internal static string FunctionTypePropSet {
            get {
                return ResourceManager.GetString("FunctionTypePropSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Objects.
        /// </summary>
        internal static string GlobalObjectsHeader {
            get {
                return ResourceManager.GetString("GlobalObjectsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error processing input XML: {0}.
        /// </summary>
        internal static string InputXmlError {
            get {
                return ResourceManager.GetString("InputXmlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid switch: {0}.
        /// </summary>
        internal static string InvalidArgument {
            get {
                return ResourceManager.GetString("InvalidArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid switch argument {0} for switch -{1}.
        /// </summary>
        internal static string InvalidSwitchArg {
            get {
                return ResourceManager.GetString("InvalidSwitchArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -MAP and -XML switches are not compatible.
        /// </summary>
        internal static string MapAndXmlArgs {
            get {
                return ResourceManager.GetString("MapAndXmlArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -O parameter must be followed by symbol map file path.
        /// </summary>
        internal static string MapArgNeedsPath {
            get {
                return ResourceManager.GetString("MapArgNeedsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function.
        /// </summary>
        internal static string MemberInfoBuiltInMethod {
            get {
                return ResourceManager.GetString("MemberInfoBuiltInMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to property.
        /// </summary>
        internal static string MemberInfoBuiltInProperty {
            get {
                return ResourceManager.GetString("MemberInfoBuiltInProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class.
        /// </summary>
        internal static string MemberInfoClass {
            get {
                return ResourceManager.GetString("MemberInfoClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to const.
        /// </summary>
        internal static string MemberInfoConst {
            get {
                return ResourceManager.GetString("MemberInfoConst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  [defined ({0},{1})].
        /// </summary>
        internal static string MemberInfoDefinedLocation {
            get {
                return ResourceManager.GetString("MemberInfoDefinedLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   {0} [{1}{2}]{3}{4}.
        /// </summary>
        internal static string MemberInfoFormat {
            get {
                return ResourceManager.GetString("MemberInfoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function.
        /// </summary>
        internal static string MemberInfoFunction {
            get {
                return ResourceManager.GetString("MemberInfoFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function expression.
        /// </summary>
        internal static string MemberInfoFunctionExpression {
            get {
                return ResourceManager.GetString("MemberInfoFunctionExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to literal var.
        /// </summary>
        internal static string MemberInfoLiteral {
            get {
                return ResourceManager.GetString("MemberInfoLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to possibly undefined.
        /// </summary>
        internal static string MemberInfoPossiblyUndefined {
            get {
                return ResourceManager.GetString("MemberInfoPossiblyUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0} references].
        /// </summary>
        internal static string MemberInfoReferences {
            get {
                return ResourceManager.GetString("MemberInfoReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exported .
        /// </summary>
        internal static string MemberInfoScopeExported {
            get {
                return ResourceManager.GetString("MemberInfoScopeExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to global.
        /// </summary>
        internal static string MemberInfoScopeGlobal {
            get {
                return ResourceManager.GetString("MemberInfoScopeGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to built-in Global .
        /// </summary>
        internal static string MemberInfoScopeGlobalObject {
            get {
                return ResourceManager.GetString("MemberInfoScopeGlobalObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local .
        /// </summary>
        internal static string MemberInfoScopeLocal {
            get {
                return ResourceManager.GetString("MemberInfoScopeLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to outer .
        /// </summary>
        internal static string MemberInfoScopeOuter {
            get {
                return ResourceManager.GetString("MemberInfoScopeOuter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to argument.
        /// </summary>
        internal static string MemberInfoTypeArgument {
            get {
                return ResourceManager.GetString("MemberInfoTypeArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to arguments array.
        /// </summary>
        internal static string MemberInfoTypeArguments {
            get {
                return ResourceManager.GetString("MemberInfoTypeArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to catch error.
        /// </summary>
        internal static string MemberInfoTypeCatchEror {
            get {
                return ResourceManager.GetString("MemberInfoTypeCatchEror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to super.
        /// </summary>
        internal static string MemberInfoTypeSuper {
            get {
                return ResourceManager.GetString("MemberInfoTypeSuper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var.
        /// </summary>
        internal static string MemberInfoVar {
            get {
                return ResourceManager.GetString("MemberInfoVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to object property.
        /// </summary>
        internal static string MemberInfoWithField {
            get {
                return ResourceManager.GetString("MemberInfoWithField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [or lexical declaration].
        /// </summary>
        internal static string MemberInfoWithLexDecl {
            get {
                return ResourceManager.GetString("MemberInfoWithLexDecl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [or lexical function].
        /// </summary>
        internal static string MemberInfoWithLexFunc {
            get {
                return ResourceManager.GetString("MemberInfoWithLexFunc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [or {0}{1}].
        /// </summary>
        internal static string MemberInfoWithPossibly {
            get {
                return ResourceManager.GetString("MemberInfoWithPossibly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minifying from STDIN.
        /// </summary>
        internal static string MinifyFromStdIn {
            get {
                return ResourceManager.GetString("MinifyFromStdIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combining and minifying:.
        /// </summary>
        internal static string MinifyingMultipleInputs {
            get {
                return ResourceManager.GetString("MinifyingMultipleInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minifying &apos;{0}&apos;.
        /// </summary>
        internal static string MinifySingleInput {
            get {
                return ResourceManager.GetString("MinifySingleInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See the &apos;-?&apos; command-line option for usage details..
        /// </summary>
        internal static string MiniUsageMessage {
            get {
                return ResourceManager.GetString("MiniUsageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   [Module has default export].
        /// </summary>
        internal static string ModuleHasDefaultExport {
            get {
                return ResourceManager.GetString("ModuleHasDefaultExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [incomplete].
        /// </summary>
        internal static string ModuleIncompleteFlag {
            get {
                return ResourceManager.GetString("ModuleIncompleteFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [implicit].
        /// </summary>
        internal static string ModuleNameImplicit {
            get {
                return ResourceManager.GetString("ModuleNameImplicit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol map file already specified.
        /// </summary>
        internal static string MultipleMapArg {
            get {
                return ResourceManager.GetString("MultipleMapArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output file already specified.
        /// </summary>
        internal static string MultipleOutputArg {
            get {
                return ResourceManager.GetString("MultipleOutputArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot specify multiple -XML arguments.
        /// </summary>
        internal static string MultipleXmlArgs {
            get {
                return ResourceManager.GetString("MultipleXmlArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File already exists and clobber option is not set to true. Output not created: {0}.
        /// </summary>
        internal static string NoClobberError {
            get {
                return ResourceManager.GetString("NoClobberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No input files to process.
        /// </summary>
        internal static string NoInput {
            get {
                return ResourceManager.GetString("NoInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No parsed code block.
        /// </summary>
        internal static string NoParsedCode {
            get {
                return ResourceManager.GetString("NoParsedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT KNOWN.
        /// </summary>
        internal static string NotKnown {
            get {
                return ResourceManager.GetString("NotKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -O parameter must be followed by output path.
        /// </summary>
        internal static string OutputArgNeedsPath {
            get {
                return ResourceManager.GetString("OutputArgNeedsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minified output is EMPTY!.
        /// </summary>
        internal static string OutputEmpty {
            get {
                return ResourceManager.GetString("OutputEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output file returned an error code: {0}.
        /// </summary>
        internal static string OutputFileError {
            get {
                return ResourceManager.GetString("OutputFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to output file.
        /// </summary>
        internal static string OutputFileErrorSubCat {
            get {
                return ResourceManager.GetString("OutputFileErrorSubCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output group #{0} returned an error code: {1}.
        /// </summary>
        internal static string OutputGroupError {
            get {
                return ResourceManager.GetString("OutputGroupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to output group.
        /// </summary>
        internal static string OutputGroupErrorSubCat {
            get {
                return ResourceManager.GetString("OutputGroupErrorSubCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretty-print (-PRETTY) and Echo-input (-ECHO) switches are not compatible.
        /// </summary>
        internal static string PrettyAndEchoArgs {
            get {
                return ResourceManager.GetString("PrettyAndEchoArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing resource script {0}....
        /// </summary>
        internal static string ReadingResourceFile {
            get {
                return ResourceManager.GetString("ReadingResourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename switch must either have valid parameter parts or be followed by valid file path.
        /// </summary>
        internal static string RenameArgMissingParameterOrFilePath {
            get {
                return ResourceManager.GetString("RenameArgMissingParameterOrFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource argument &apos;{0}&apos; must be valid boolean or numeric literal.
        /// </summary>
        internal static string ResourceArgInvalidName {
            get {
                return ResourceManager.GetString("ResourceArgInvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid resource file type: {0}. Must be .JS, .RESX, or .RESOURCES..
        /// </summary>
        internal static string ResourceArgInvalidType {
            get {
                return ResourceManager.GetString("ResourceArgInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -RES parameter must be followed by path to existing resource file.
        /// </summary>
        internal static string ResourceArgNeedsPath {
            get {
                return ResourceManager.GetString("ResourceArgNeedsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gzip of minified output approx. {0} bytes ({1}% compression).
        /// </summary>
        internal static string SavingsGzipMessage {
            get {
                return ResourceManager.GetString("SavingsGzipMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gzip of source input approx. {0} bytes ({1}% compression).
        /// </summary>
        internal static string SavingsGzipSourceMessage {
            get {
                return ResourceManager.GetString("SavingsGzipSourceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Size: {0} bytes; reduced size: {1} bytes ({2}% minification).
        /// </summary>
        internal static string SavingsMessage {
            get {
                return ResourceManager.GetString("SavingsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [strict].
        /// </summary>
        internal static string ScopeIsStrictFlag {
            get {
                return ResourceManager.GetString("ScopeIsStrictFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source file cannot be a folder: {0}.
        /// </summary>
        internal static string SourceFileIsFolder {
            get {
                return ResourceManager.GetString("SourceFileIsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source file does not exist: {0}.
        /// </summary>
        internal static string SourceFileNotExist {
            get {
                return ResourceManager.GetString("SourceFileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing Nodes.
        /// </summary>
        internal static string StepAnalyzeNode {
            get {
                return ResourceManager.GetString("StepAnalyzeNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing Scopes.
        /// </summary>
        internal static string StepAnalyzeScope {
            get {
                return ResourceManager.GetString("StepAnalyzeScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-Renaming.
        /// </summary>
        internal static string StepAutoRename {
            get {
                return ResourceManager.GetString("StepAutoRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluating Literals.
        /// </summary>
        internal static string StepEvaluateLiterals {
            get {
                return ResourceManager.GetString("StepEvaluateLiterals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Pass.
        /// </summary>
        internal static string StepFinalPass {
            get {
                return ResourceManager.GetString("StepFinalPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing.
        /// </summary>
        internal static string StepParse {
            get {
                return ResourceManager.GetString("StepParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reordering.
        /// </summary>
        internal static string StepReorder {
            get {
                return ResourceManager.GetString("StepReorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolving References.
        /// </summary>
        internal static string StepResolve {
            get {
                return ResourceManager.GetString("StepResolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating Generated Names.
        /// </summary>
        internal static string StepValidateNames {
            get {
                return ResourceManager.GetString("StepValidateNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch -{0} requires an argument.
        /// </summary>
        internal static string SwitchRequiresArg {
            get {
                return ResourceManager.GetString("SwitchRequiresArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse time: {1:F0}ms..
        /// </summary>
        internal static string TimerFormat {
            get {
                return ResourceManager.GetString("TimerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse time for input group {0}: {1:F0}ms..
        /// </summary>
        internal static string TimerMultiFormat {
            get {
                return ResourceManager.GetString("TimerMultiFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Step {0}: {1,4:F0}ms {2}.
        /// </summary>
        internal static string TimerStepFormat {
            get {
                return ResourceManager.GetString("TimerStepFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined Global References:.
        /// </summary>
        internal static string UndefinedGlobalHeader {
            get {
                return ResourceManager.GetString("UndefinedGlobalHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   {0} [{3}] at Line {1}, Column {2}.
        /// </summary>
        internal static string UndefinedInfo {
            get {
                return ResourceManager.GetString("UndefinedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown input type. Please use either the -JS or -CSS switch..
        /// </summary>
        internal static string UnknownInputType {
            get {
                return ResourceManager.GetString("UnknownInputType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNREACHABLE.
        /// </summary>
        internal static string Unreachable {
            get {
                return ResourceManager.GetString("Unreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot specify -XML argument AND input files.
        /// </summary>
        internal static string XmlArgHasInputFiles {
            get {
                return ResourceManager.GetString("XmlArgHasInputFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument -XML must be followed by XML file path.
        /// </summary>
        internal static string XmlArgNeedsPath {
            get {
                return ResourceManager.GetString("XmlArgNeedsPath", resourceCulture);
            }
        }
    }
}
